import { ToolDefinition, ToolId, ToolCategory } from '@/types';

/**
 * Tool configuration registry — the single source of truth for every tool.
 * Routes, navigation, search, option panels, and API wiring all derive from here.
 * Adding a new tool requires only adding an entry here and (optionally) one options panel.
 */

const MB = 1024 * 1024;

export const TOOLS: Record<ToolId, ToolDefinition> = {
  // ============================================================================
  // ORGANIZE PDF TOOLS
  // ============================================================================
  merge: {
    id: 'merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one document',
    category: 'merge',
    icon: 'layers',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 20,
    minFiles: 2,
    maxFileSize: 50 * MB,
    route: '/merge',
    navGroup: 'organize',
    keywords: ['combine', 'join', 'concatenate'],
    popular: true,
    actionLabel: (count) => (count > 1 ? `Merge ${count} PDFs` : 'Merge PDFs'),
  },
  split: {
    id: 'split',
    name: 'Split PDF',
    description: 'Separate one PDF into multiple documents',
    category: 'split',
    icon: 'scissors',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 1,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/split',
    navGroup: 'organize',
    keywords: ['separate', 'divide', 'pages'],
    optionsPanel: 'split',
    defaultOptions: { mode: 'all' },
    needsPageCount: true,
    popular: true,
    actionLabel: () => 'Split PDF',
  },
  reorder: {
    id: 'reorder',
    name: 'Reorder Pages',
    description: 'Rearrange pages within a PDF document',
    category: 'organize',
    icon: 'arrow-up-down',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 1,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/reorder',
    navGroup: 'organize',
    navLabel: 'Organize PDF',
    keywords: ['organize', 'rearrange', 'sort', 'move pages'],
    optionsPanel: 'reorder',
    needsPageCount: true,
    actionLabel: () => 'Reorder Pages',
  },
  'remove-pages': {
    id: 'remove-pages',
    name: 'Remove Pages',
    description: 'Remove specific pages from a PDF document',
    category: 'organize',
    icon: 'file-minus',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 1,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/remove-pages',
    navGroup: 'organize',
    keywords: ['delete pages', 'cut'],
    optionsPanel: 'page-selection',
    needsPageCount: true,
    actionLabel: () => 'Remove Pages',
  },
  'extract-pages': {
    id: 'extract-pages',
    name: 'Extract Pages',
    description: 'Extract specific pages into a new PDF',
    category: 'organize',
    icon: 'file-output',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 1,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/extract-pages',
    navGroup: 'organize',
    keywords: ['pull pages', 'select pages'],
    optionsPanel: 'page-selection',
    needsPageCount: true,
    actionLabel: () => 'Extract Pages',
  },
  'scan-to-pdf': {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    description: 'Convert scanned images to PDF with optional OCR',
    category: 'convert',
    icon: 'scan',
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp', 'image/jpeg', 'image/png', 'image/webp'],
    maxFiles: 20,
    minFiles: 1,
    maxFileSize: 20 * MB,
    route: '/scan-to-pdf',
    navGroup: 'organize',
    keywords: ['scanner', 'photo', 'image', 'ocr'],
    optionsPanel: 'scan',
    defaultOptions: { ocr: false, language: 'en' },
    actionLabel: (count) => (count > 1 ? `Convert ${count} scans` : 'Convert to PDF'),
  },

  // ============================================================================
  // OPTIMIZE PDF TOOLS
  // ============================================================================
  compress: {
    id: 'compress',
    name: 'Compress PDF',
    description: 'Reduce file size while maintaining quality',
    category: 'compress',
    icon: 'minimize-2',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 10,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/compress',
    navGroup: 'optimize',
    keywords: ['reduce', 'shrink', 'optimize', 'smaller'],
    optionsPanel: 'compress',
    defaultOptions: { quality: 'medium' },
    supportsBatch: true,
    popular: true,
    actionLabel: (count) => (count > 1 ? `Compress ${count} PDFs` : 'Compress PDF'),
  },
  ocr: {
    id: 'ocr',
    name: 'OCR PDF',
    description: 'Add searchable text layer to scanned PDFs',
    category: 'ocr',
    icon: 'scan-text',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/ocr',
    navGroup: 'optimize',
    keywords: ['text recognition', 'searchable', 'extract text'],
    optionsPanel: 'ocr',
    defaultOptions: { language: 'en' },
    supportsBatch: true,
    popular: true,
    actionLabel: (count) => (count > 1 ? `Run OCR on ${count} PDFs` : 'Run OCR'),
  },
  'repair-pdf': {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Fix corrupted or damaged PDF files',
    category: 'organize',
    icon: 'wrench',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 1,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/repair-pdf',
    navGroup: 'optimize',
    keywords: ['fix', 'corrupted', 'damaged', 'recover'],
    actionLabel: () => 'Repair PDF',
  },

  // ============================================================================
  // CONVERT FROM PDF TOOLS
  // ============================================================================
  'pdf-to-word': {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF documents to editable Word files',
    category: 'convert',
    icon: 'file-text',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/pdf-to-word',
    navGroup: 'convert-from-pdf',
    keywords: ['docx', 'doc', 'editable'],
    outputFormat: 'docx',
    optionsPanel: 'convert-info',
    popular: true,
  },
  'pdf-to-excel': {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract tables from PDFs to Excel spreadsheets',
    category: 'convert',
    icon: 'table',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/pdf-to-excel',
    navGroup: 'convert-from-pdf',
    keywords: ['xlsx', 'spreadsheet', 'tables'],
    outputFormat: 'xlsx',
    optionsPanel: 'convert-info',
  },
  'pdf-to-image': {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Convert PDF pages to PNG images',
    category: 'convert',
    icon: 'image',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/pdf-to-image',
    navGroup: 'convert-from-pdf',
    navLabel: 'PDF to JPG',
    keywords: ['jpg', 'jpeg', 'png', 'picture'],
    outputFormat: 'png',
    optionsPanel: 'convert-info',
    popular: true,
  },
  'pdf-to-ppt': {
    id: 'pdf-to-ppt',
    name: 'PDF to PowerPoint',
    description: 'Convert PDF to PowerPoint presentation',
    category: 'convert',
    icon: 'presentation',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/pdf-to-ppt',
    navGroup: 'convert-from-pdf',
    keywords: ['pptx', 'slides', 'presentation'],
    outputFormat: 'pptx',
    optionsPanel: 'convert-info',
  },
  'pdf-to-html': {
    id: 'pdf-to-html',
    name: 'PDF to HTML',
    description: 'Convert PDF to HTML with embedded images',
    category: 'convert',
    icon: 'code',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/pdf-to-html',
    navGroup: 'convert-from-pdf',
    keywords: ['web', 'webpage'],
    outputFormat: 'html',
    optionsPanel: 'convert-info',
  },
  'pdf-to-text': {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    description: 'Extract text content from PDF documents',
    category: 'convert',
    icon: 'file-type',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/pdf-to-text',
    navGroup: 'convert-from-pdf',
    keywords: ['txt', 'plain text', 'extract'],
    outputFormat: 'txt',
    optionsPanel: 'convert-info',
  },
  'pdf-to-pdfa': {
    id: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    description: 'Convert PDF to archival format (PDF/A-2b)',
    category: 'convert',
    icon: 'archive',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/pdf-to-pdfa',
    navGroup: 'convert-from-pdf',
    keywords: ['archive', 'archival', 'compliance'],
    outputFormat: 'pdfa',
    optionsPanel: 'convert-info',
  },

  // ============================================================================
  // CONVERT TO PDF TOOLS
  // ============================================================================
  'word-to-pdf': {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF format',
    category: 'convert',
    icon: 'file',
    acceptedFileTypes: ['.doc', '.docx', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/word-to-pdf',
    navGroup: 'convert-to-pdf',
    keywords: ['docx', 'doc', 'document'],
    outputFormat: 'pdf',
    optionsPanel: 'convert-info',
    popular: true,
  },
  'excel-to-pdf': {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF format',
    category: 'convert',
    icon: 'file-spreadsheet',
    acceptedFileTypes: ['.xls', '.xlsx', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/excel-to-pdf',
    navGroup: 'convert-to-pdf',
    keywords: ['xlsx', 'xls', 'spreadsheet'],
    outputFormat: 'pdf',
    optionsPanel: 'convert-info',
  },
  'image-to-pdf': {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert images to a PDF document',
    category: 'convert',
    icon: 'file-image',
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp', 'image/jpeg', 'image/png', 'image/webp'],
    maxFiles: 20,
    minFiles: 1,
    maxFileSize: 20 * MB,
    route: '/image-to-pdf',
    navGroup: 'convert-to-pdf',
    navLabel: 'JPG to PDF',
    keywords: ['jpg', 'jpeg', 'png', 'picture', 'photo'],
    outputFormat: 'pdf',
    optionsPanel: 'convert-info',
    popular: true,
  },
  'powerpoint-to-pdf': {
    id: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert PowerPoint presentations to PDF format',
    category: 'convert',
    icon: 'presentation',
    acceptedFileTypes: ['.ppt', '.pptx', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/powerpoint-to-pdf',
    navGroup: 'convert-to-pdf',
    keywords: ['pptx', 'ppt', 'slides'],
    outputFormat: 'pdf',
    optionsPanel: 'convert-info',
  },
  'html-to-pdf': {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert HTML files to PDF format',
    category: 'convert',
    icon: 'code',
    acceptedFileTypes: ['.html', '.htm', 'text/html'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/html-to-pdf',
    navGroup: 'convert-to-pdf',
    keywords: ['web', 'webpage'],
    outputFormat: 'pdf',
    optionsPanel: 'convert-info',
  },

  // ============================================================================
  // CONVERT TO LIBREOFFICE TOOLS
  // ============================================================================
  'pdf-to-odt': {
    id: 'pdf-to-odt',
    name: 'PDF to ODT',
    description: 'Convert PDF documents to LibreOffice Writer format',
    category: 'convert',
    icon: 'file-text',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/pdf-to-odt',
    navGroup: 'libreoffice',
    keywords: ['libreoffice', 'writer', 'openoffice'],
    outputFormat: 'odt',
    optionsPanel: 'convert-info',
  },
  'pdf-to-ods': {
    id: 'pdf-to-ods',
    name: 'PDF to ODS',
    description: 'Convert PDF documents to LibreOffice Calc format',
    category: 'convert',
    icon: 'table',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/pdf-to-ods',
    navGroup: 'libreoffice',
    keywords: ['libreoffice', 'calc', 'spreadsheet'],
    outputFormat: 'ods',
    optionsPanel: 'convert-info',
  },
  'pdf-to-odp': {
    id: 'pdf-to-odp',
    name: 'PDF to ODP',
    description: 'Convert PDF documents to LibreOffice Impress format',
    category: 'convert',
    icon: 'presentation',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/pdf-to-odp',
    navGroup: 'libreoffice',
    keywords: ['libreoffice', 'impress', 'slides'],
    outputFormat: 'odp',
    optionsPanel: 'convert-info',
  },
  'word-to-odt': {
    id: 'word-to-odt',
    name: 'Word to ODT',
    description: 'Convert Word documents to LibreOffice Writer format',
    category: 'convert',
    icon: 'file',
    acceptedFileTypes: ['.doc', '.docx', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/word-to-odt',
    navGroup: 'libreoffice',
    keywords: ['libreoffice', 'writer', 'docx'],
    outputFormat: 'odt',
    optionsPanel: 'convert-info',
  },
  'excel-to-ods': {
    id: 'excel-to-ods',
    name: 'Excel to ODS',
    description: 'Convert Excel spreadsheets to LibreOffice Calc format',
    category: 'convert',
    icon: 'file-spreadsheet',
    acceptedFileTypes: ['.xls', '.xlsx', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/excel-to-ods',
    navGroup: 'libreoffice',
    keywords: ['libreoffice', 'calc', 'xlsx'],
    outputFormat: 'ods',
    optionsPanel: 'convert-info',
  },
  'powerpoint-to-odp': {
    id: 'powerpoint-to-odp',
    name: 'PowerPoint to ODP',
    description: 'Convert PowerPoint presentations to LibreOffice Impress format',
    category: 'convert',
    icon: 'presentation',
    acceptedFileTypes: ['.ppt', '.pptx', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/powerpoint-to-odp',
    navGroup: 'libreoffice',
    keywords: ['libreoffice', 'impress', 'pptx'],
    outputFormat: 'odp',
    optionsPanel: 'convert-info',
  },

  // ============================================================================
  // CONVERT LIBREOFFICE TO PDF TOOLS
  // ============================================================================
  'odt-to-pdf': {
    id: 'odt-to-pdf',
    name: 'ODT to PDF',
    description: 'Convert LibreOffice Writer documents to PDF format',
    category: 'convert',
    icon: 'file',
    acceptedFileTypes: ['.odt', 'application/vnd.oasis.opendocument.text'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/odt-to-pdf',
    navGroup: 'convert-to-pdf',
    keywords: ['libreoffice', 'writer'],
    outputFormat: 'pdf',
    optionsPanel: 'convert-info',
  },
  'ods-to-pdf': {
    id: 'ods-to-pdf',
    name: 'ODS to PDF',
    description: 'Convert LibreOffice Calc spreadsheets to PDF format',
    category: 'convert',
    icon: 'file-spreadsheet',
    acceptedFileTypes: ['.ods', 'application/vnd.oasis.opendocument.spreadsheet'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/ods-to-pdf',
    navGroup: 'convert-to-pdf',
    keywords: ['libreoffice', 'calc'],
    outputFormat: 'pdf',
    optionsPanel: 'convert-info',
  },
  'odp-to-pdf': {
    id: 'odp-to-pdf',
    name: 'ODP to PDF',
    description: 'Convert LibreOffice Impress presentations to PDF format',
    category: 'convert',
    icon: 'presentation',
    acceptedFileTypes: ['.odp', 'application/vnd.oasis.opendocument.presentation'],
    maxFiles: 5,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/odp-to-pdf',
    navGroup: 'convert-to-pdf',
    keywords: ['libreoffice', 'impress'],
    outputFormat: 'pdf',
    optionsPanel: 'convert-info',
  },

  // ============================================================================
  // SECURITY TOOLS
  // ============================================================================
  'unlock-pdf': {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from PDF documents',
    category: 'security',
    icon: 'unlock',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 10,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/unlock',
    navGroup: 'security',
    keywords: ['decrypt', 'remove password', 'open'],
    optionsPanel: 'unlock',
    actionLabel: (count) => (count > 1 ? `Unlock ${count} PDFs` : 'Unlock PDF'),
  },

  // ============================================================================
  // EDIT PDF TOOLS
  // ============================================================================
  'add-page-numbers': {
    id: 'add-page-numbers',
    name: 'Add Page Numbers',
    description: 'Add page numbers to your PDF document',
    category: 'edit',
    icon: 'hash',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 1,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/add-page-numbers',
    navGroup: 'edit',
    keywords: ['numbering', 'pagination', 'footer'],
    optionsPanel: 'page-numbers',
    actionLabel: () => 'Add Page Numbers',
  },
  'edit-pdf': {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text annotations to your PDF documents',
    category: 'edit',
    icon: 'edit',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 1,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/edit-pdf',
    navGroup: 'edit',
    keywords: ['annotate', 'text', 'modify'],
    bespoke: 'edit-pdf',
    actionLabel: () => 'Apply Edits',
  },
  'sign-pdf': {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Add your signature to PDF documents',
    category: 'security',
    icon: 'pen-tool',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 1,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/sign-pdf',
    navGroup: 'security',
    keywords: ['signature', 'esign', 'autograph'],
    bespoke: 'sign-pdf',
    actionLabel: () => 'Sign PDF',
  },

  // ============================================================================
  // LEGACY TOOLS (kept for backward compatibility)
  // ============================================================================
  rotate: {
    id: 'rotate',
    name: 'Rotate Pages',
    description: 'Rotate PDF pages to the correct orientation',
    category: 'organize',
    icon: 'rotate-cw',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 1,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/rotate',
    navGroup: 'edit',
    navLabel: 'Rotate PDF',
    keywords: ['turn', 'orientation', 'landscape', 'portrait'],
    optionsPanel: 'rotate',
    defaultOptions: { rotation: 90, applyToPages: 'all' },
    supportsBatch: true,
    needsPageCount: true,
    actionLabel: () => 'Rotate PDF',
  },
  watermark: {
    id: 'watermark',
    name: 'Add Watermark',
    description: 'Add text or image watermarks to PDFs',
    category: 'watermark',
    icon: 'stamp',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 10,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/watermark',
    navGroup: 'edit',
    keywords: ['stamp', 'brand', 'overlay'],
    optionsPanel: 'watermark',
    defaultOptions: { type: 'text', text: 'CONFIDENTIAL', position: 'diagonal', opacity: 50, fontSize: 48, color: '#6366f1', scale: 30 },
    supportsBatch: true,
    popular: true,
    actionLabel: (count) => (count > 1 ? `Watermark ${count} PDFs` : 'Add Watermark'),
  },
  'password-protect': {
    id: 'password-protect',
    name: 'Protect PDF',
    description: 'Add password protection to PDF documents',
    category: 'security',
    icon: 'lock',
    acceptedFileTypes: ['.pdf', 'application/pdf'],
    maxFiles: 10,
    minFiles: 1,
    maxFileSize: 50 * MB,
    route: '/protect',
    navGroup: 'security',
    keywords: ['encrypt', 'lock', 'password', 'secure'],
    optionsPanel: 'password',
    popular: true,
    actionLabel: (count) => (count > 1 ? `Protect ${count} PDFs` : 'Protect PDF'),
  },
};

export const TOOL_CATEGORIES: Record<ToolCategory, { name: string; color: string }> = {
  merge: { name: 'Merge & Combine', color: 'tool-merge' },
  split: { name: 'Split & Extract', color: 'tool-split' },
  compress: { name: 'Compress', color: 'tool-compress' },
  convert: { name: 'Convert', color: 'tool-convert' },
  organize: { name: 'Organize', color: 'tool-organize' },
  security: { name: 'Security', color: 'tool-security' },
  ocr: { name: 'OCR', color: 'tool-ocr' },
  watermark: { name: 'Watermark', color: 'tool-watermark' },
  edit: { name: 'Edit', color: 'tool-edit' },
};

export const getToolsByCategory = (category: ToolCategory): ToolDefinition[] => {
  return Object.values(TOOLS).filter((tool) => tool.category === category);
};

export const getAllTools = (): ToolDefinition[] => {
  return Object.values(TOOLS);
};

export const getToolById = (id: ToolId): ToolDefinition | undefined => {
  return TOOLS[id];
};

export const getPopularTools = (): ToolDefinition[] => {
  return Object.values(TOOLS).filter((tool) => tool.popular);
};
